{% set name = "aiodns" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 946bdfabe743fceeeb093c8a010f5d1645f708a241be849e17edfb0e49e08cd6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pycares >=4.0.0

test:
  imports:
    - aiodns
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/saghul/aiodns
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple DNS resolver for asyncio
  description: |
    aiodns provides a simple way for doing asynchronous DNS resolutions using
    pycares.
  doc_url: https://github.com/saghul/aiodns
  dev_url: https://github.com/saghul/aiodns

extra:
  recipe-maintainers:
    - CurtLH
